/**
 * Attendance notification producers (PW-4, Phase 1).
 *
 * Only the explicit, action-triggered event lives here: an admin overriding a
 * driver's RSVP. Time-derived events (attendance opened, "you haven't RSVP'd"
 * reminders, closing soon) are generated by the Phase 3 scheduled engine, since
 * they have no synchronous request to hook into.
 *
 * The attendance domain keys on CSV `driver_id`, so we target the `drivers`
 * audience, which maps driver_ids → the linked accounts.
 */
import { notify } from "@/lib/notifications/service";
import type { AttendanceStatus } from "@/lib/attendance/types";

export async function notifyAttendanceChangedByAdmin(args: {
  driverId: string;
  raceId: string;
  raceName: string;
  raceNameHe: string;
  status: AttendanceStatus;
}): Promise<void> {
  await notify({
    type: "attendance_changed_by_admin",
    audience: { kind: "drivers", driverIds: [args.driverId] },
    // Both language variants are stored so the item renders in the viewer's
    // locale (EN template reads `race`, HE reads `raceHe`).
    params: {
      race: args.raceName,
      raceHe: args.raceNameHe || args.raceName,
      status: args.status,
    },
    // One notification per (race, driver, status) — re-saving the same status
    // won't re-notify; a genuine change to a different status will.
    dedupeKey: `${args.raceId}:${args.driverId}:${args.status}`,
  });
}
